feat: 리덕스, reselect 적용
bear-bear-bear/mogakco pull request #12
Opened 2021-03-09 06:32 UTC by wscrg

2021-03-09 06:36 UTC, galaxy4276 commented
ㅋㅋㅋㅋ 백단 린트에서 걸려버리네 여기도.
서버설정 브랜치에서 수정을 해두긴했는데요

2021-03-09 06:48 UTC, wscrg commented
린트 걸리는 거 너무 귀찮아요

2021-03-09 06:48 UTC, wscrg commented
빨리 수정해줘요 백님 현기증나니까

2021-03-09 06:49 UTC, galaxy4276 commented
안해야징 ㅋㅋ 🤞

2021-03-09 06:51 UTC, wscrg commented
밥 먹고 올 동안 해두도록 하세요

2021-03-15 13:05 UTC, galaxy4276 approved these changes
자네가 최고야~

2021-03-15 14:30 UTC, galaxy4276 commented on container/TodosContainer.jsx
> +const makeMapStateToProps = () => {
Container 방식에서 더 간결한 방식으로 변경해주세요.

2021-03-15 16:51 UTC, bear-bear-bear commented on store/configureStore.js
> +  const store = createStore(rootReducer, enhancer);
`return createStore(rootReducer, enhancer)`

이렇게 바로 내보내도 직관성에 문제 없을 것 같아요! 함수 이름이 이미 명시적이라서

2021-03-15 16:52 UTC, bear-bear-bear commented on store/configureStore.js
> +  const enhancer =
쌌다...

2021-03-15 17:04 UTC, bear-bear-bear commented on container/CounterContainer.jsx
> +  };
``` javascript
const mapStateToProps = state => ({ num: getCounter(state) });
```

이렇게 바꿀 수 있어요

2021-03-15 17:08 UTC, bear-bear-bear commented on container/CounterContainer.jsx
> +};
``` javascript
const mapDispatchToProps = dispatch => ({
    increase: () => dispatch(increase()),
    decrease: () => dispatch(decrease()),
});
```

이렇게 바꿀 수 있어요

2021-03-15 17:15 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
``` js
onClick={() => dispatch(increase())}
```

이렇게 쓸 수 있어요

2021-03-15 17:15 UTC, bear-bear-bear commented on components/Counter.jsx
> +      >
얘두요

2021-03-15 17:30 UTC, bear-bear-bear requested changes
- 컨테이너 컴포넌트에서 처리해야할 redux 관련 작업이 프레젠테이셔널 컴포넌트에서 처리되고 있어요. 수정해주세요~
- useDispatch는 useCallback과 함께 사용해주세요
- 리다기 679p나오는 useActions 커스텀 훅 사용할 때가 온 것 같네요 두근

2021-03-15 17:33 UTC, bear-bear-bear commented on container/TodosContainer.jsx
> +  };
``` js
const mapStateToProps = (state, props) => ({
    input: getInputText(state),
    todos: getTodos(state, props),
)};
```

2021-03-15 17:36 UTC, bear-bear-bear commented on store/configureStore.js
> +  return store;
``` js
return createStore(rootReducer, enhancer);
```
함수 이름이 이미 명시적이라 이렇게 바로 내보내는게 더 직관적인 것 같아요

2021-03-16 02:01 UTC, wscrg commented on container/CounterContainer.jsx
> +  };
그렇네요! 감사합니다!!

2021-03-16 02:02 UTC, wscrg commented on components/Counter.jsx
> +        }}
그렇게 하면 dispatch한 결과를 리턴하게 돼요. 제가 의도한 것은 dispatch만 하는 동작이기 때문에 저렇게 작성했습니다.

2021-03-16 02:06 UTC, wscrg commented
> * 컨테이너 컴포넌트에서 처리해야할 redux 관련 작업이 프레젠테이셔널 컴포넌트에서 처리되고 있어요. 수정해주세요~
> * useDispatch는 useCallback과 함께 사용해주세요
> * 다수 액션 생성 함수에 대해 디스패치 함수로 변환하는 반복작업이 보이고 있어요! 리다기 679p나오는 useActions 커스텀 훅 사용할 때가 온 것 같네요 두근
> 
> 딱 어제 공부한 리다기 내용이라 감히 리뷰할 수 있었어요. 제 코드때도 엄한 리뷰 부탁드려요 사랑해요

1. 아마 앞으로 useSelector와 reselect를 사용하여 리덕스의 상태값을 참조하게 될 것 같아요. 그렇게되면 container라는 디렉토리는 필요가 없어집니다. 컴포넌트단에서 모두 처리하기 때문이에요. 이 부분은 상의하도록 합시다.
2. 수정 중에 있습니다.
3. 이것도 해봐야겠네요!! 감사합니다

2021-03-16 07:26 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
똑같이 함수를 리턴하게 될거에요 :) 변경해보세용

2021-03-16 07:36 UTC, bear-bear-bear approved these changes
reselect에 대해 무지한 상태로 말했네요 동작하는 방식이 또 다른가보군요;; 공부해오겠습니다.

2021-03-16 07:52 UTC, merged

2021-03-16 08:03 UTC, wscrg commented on components/Counter.jsx
> +        }}
> 똑같이 함수를 리턴하게 될거에요 :) 변경해보세용

() => (console.log(1))은 () => { return { console.log(1); } } 과 같아요.
() => { console.log(1); } 은 실행되면 console.log(1)을 실행하고 그대로 종료됩니다. 함수를 리턴하지 않습니다.
위 코드는 increase 액션 크리에이터로 생성된 액션 객체를 dispatch를 한다는 의미의 코드이기 때문에 위와 같이 작성한 것입니다.

2021-03-16 08:14 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
jsx가 렌더링 되면 onClick에 콜백함수가 담기게 됩니다. 우리 목적은 onClick에 dispatch를 실행시키는 콜백함수를 담는거죠.  작성해주신  `onClick={() => { dispatch(increase()); }}` 는 '내부에서 dispatch를 실행하는 함수를 onClick에 담아라' 라는 뜻이고, 중괄호를 생략한  `onClick={() => dispatch(increase())}` 은  'dispatch를 실행하는 함수를 onClick에 담아라' 라는 뜻입니다. 물론 둘은 의미는 다르지만, 저희가 기대하는 동작은 똑같이 수행해요. 그래서 생략이 가능합니다 :)

2021-03-16 08:18 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
``` js
const onClick1 = () => console.log('a');
const onClick2 = () => {
     console.log('a');
}

onClick1(); // 'a'
onClick2(); // 'a'
```

이렇게 이해하시면 될 것 같아요. 저또한 엄청 헷갈린 부분.. 리다기에서도 암말 없이 생략해버리는데 설명도 안해주고;

2021-03-16 08:18 UTC, wscrg commented on components/Counter.jsx
> +        }}
아닙니다. onClick={() => dispatch(increase())}는 'dispatch를 실행한 결과를 리턴하는 콜백 함수'입니다. 실행에 있어서 큰 문제는 없을지라도 의미상 혼동될 수 있습니다.

2021-03-16 08:42 UTC, wscrg commented on components/Counter.jsx
> +        }}
`
const sum = (a, b) => a+b
const a = () => sum(1, 2)
const b = () => { sum(1, 2) }
const c = a();  // 3
const d = b(); // undefined
`

2021-03-16 08:43 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
실시간 변경 관람중

2021-03-16 08:44 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
아 예제 보니끼 확실히 이해 되네요

2021-03-16 08:45 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
피드백하다 피드백 받아버렷

2021-03-16 08:45 UTC, bear-bear-bear commented on components/Counter.jsx
> +        }}
감사합니다 ㄹㅇ 통수맞은 기분

2021-03-16 08:46 UTC, wscrg commented on components/Counter.jsx
> +        }}
이것이 코드 리뷰의 긍정적 영향인가.. 가슴이 웅장해진다