feat: 입력값 취소 버튼이 있는 이메일 컴포넌트 추가
bear-bear-bear/mogakco pull request #136
Opened 2021-06-06 16:55 UTC by bear-bear-bear

2021-06-06 18:13 UTC, galaxy4276 requested changes

2021-06-06 18:13 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
리액트 훅이 조건문 안에 들어가도 되나요?

2021-06-06 18:13 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
```suggestion
      dispatch(verifyEmailRequest(verifiedEmail));
```
![image](https://user-images.githubusercontent.com/50310464/120935562-5a311d00-c73e-11eb-960f-52146673ef8b.png)

2021-06-07 03:21 UTC, bear-bear-bear commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
``` js
const [value, setValue] = useState('');
if (...) {
  alert(value)
}
```
위 코드가 가능한 것과 같은 맥락인 듯 하네요. useDispatch를 if문 안에서 사용했다면 오류였고 eslint부터가 이미 잡아냈을 테지만, 전 if문 안에서 훅스를 쓴게 아니라 훅스의 리턴값을 쓴겁디당

2021-06-07 03:23 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
확인!

2021-06-07 03:24 UTC, galaxy4276 approved these changes

2021-06-07 03:24 UTC, bear-bear-bear commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
님 잠결에 리뷰했져?

2021-06-07 03:26 UTC, galaxy4276 requested changes
타임

2021-06-07 03:26 UTC, bear-bear-bear commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
근데 쿼리로 온 이메일 재검증이니 verifiedEmail 보단 queryEmail이 맞겠네요 수정해야겠다 감사합니당

2021-06-07 03:27 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
dispatch 는
` const dispatch = useDispatch();`
이렇게 끌어오는것 아닌가요?

2021-06-07 03:28 UTC, bear-bear-bear commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
맞져 그것또한 훅스가 아닌 훅스의 리턴값

2021-06-07 03:29 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
https://stackoverflow.com/questions/58543102/using-reduxs-usedispatch-in-a-custom-hook-yields-an-error

2021-06-07 03:32 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
훅스의 리턴값이 훅스일수 있어서요

2021-06-07 03:41 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
dispatch는 if 문 내부에서 사용해도 되는 것 같습니다 감사합니다 ㅎ

2021-06-07 03:41 UTC, galaxy4276 approved these changes

2021-06-07 03:42 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
https://stackoverflow.com/questions/46810526/react-redux-dispatch-2-actions-based-on-condition

2021-06-07 03:46 UTC, galaxy4276 commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
https://www.digitalocean.com/community/tutorials/redux-redux-thunk

2021-06-07 04:15 UTC, bear-bear-bear commented on next/components/signup/Auth/index.js
> +      dispatch(verifyEmailRequest(verifiedEmail));
훅스의 리턴이 훅스일수도 있군요 덕분에 알아갑니다

2021-06-07 04:16 UTC, bear-bear-bear commented
풀어즈ㅓ 빼액

2021-06-07 04:17 UTC, galaxy4276 commented
> 풀어즈ㅓ 빼액

1분 뒤 내가 머지

2021-06-07 04:17 UTC, merged