REFACTOR: 회원가입 >OptionalInfo 페이지 리팩터링
bear-bear-bear/mogakco pull request #165
Opened 2021-06-17 15:49 UTC by galaxy4276

# Todo
- [x] select 데이터 처리 수정하기
- [ ] useEffect 걷어내기
- [ ] 관련 redux, component 타입 입히기

### 작성중입니다.

2021-06-17 15:51 UTC, bear-bear-bear commented
무지성 approve!

2021-06-17 15:51 UTC, bear-bear-bear commented
approve인 줄 알았지만 코멘트!

2021-06-17 15:54 UTC, bear-bear-bear requested changes

2021-06-17 15:54 UTC, bear-bear-bear commented on next/components/common/Label/index.tsx
> + * direction은 정의할 input의 상대적인 방향을 말합니다. 해당 방향으로 margin  이 적용됩니다.
띄어쓰기 한 번 빼주세요 불편하네요

2021-06-17 15:56 UTC, galaxy4276 commented on next/components/common/Label/index.tsx
> + * direction은 정의할 input의 상대적인 방향을 말합니다. 해당 방향으로 margin  이 적용됩니다.
앜ㅋㅋㅋㅋ 이거 웹스톰 한글이랑 영어붙어있으면 뭐라해서 편집증 발동함...

2021-06-17 16:01 UTC, bear-bear-bear commented on next/components/common/Label/index.tsx
> + * direction은 정의할 input의 상대적인 방향을 말합니다. 해당 방향으로 margin  이 적용됩니다.
아녀 두개인거 한개로 빼주시란 소리예욧!

2021-06-17 16:01 UTC, bear-bear-bear commented on next/components/common/Label/index.tsx
> + * direction은 정의할 input의 상대적인 방향을 말합니다. 해당 방향으로 margin  이 적용됩니다.
`margin  이` >> `margin 이`

2021-06-17 16:02 UTC, bear-bear-bear commented on next/components/common/Label/index.tsx
> + * direction은 정의할 input의 상대적인 방향을 말합니다. 해당 방향으로 margin  이 적용됩니다.
![image](https://user-images.githubusercontent.com/57123802/122433076-d9411380-cfd0-11eb-9aa0-ad54407569df.png)

2021-06-18 10:49 UTC, bear-bear-bear requested changes
생각해주셔 코드 싹 다 변경해주신 점 감사해요 :):):) 도움 없었으면 고난이 컸을 듯..

2021-06-18 10:49 UTC, bear-bear-bear commented on next/hooks/useAppDispatch.ts
> +const useAppDispatch = () => useDispatch<AppDispatch>();
`useTypedDispatch`가 더 명시적이지 않을까용? App이란 이름은 한번 보고 무슨 차인지 알기 힘들었어요

2021-06-18 10:49 UTC, bear-bear-bear commented on next/hooks/useAppSelector.ts
> +const useAppSelector: TypedUseSelectorHook<RootState> = useSelector;
여기두 `useTypedSelector`

2021-06-18 10:49 UTC, bear-bear-bear commented on next/typings/auth.ts
> +  signUpError: string | null;
각 Error 상태에는 `AxiosError | string | null` 이 들어가요. 제 타입스크립트 지식이 부족해서 `AxiosError` 타입을 어떻게 명시해야 할진 모르겠네요..` lib/apiClient`에 있는 `getAxiosError`에서 Error 상태에 들어가게 되는 리턴값들을 확인할 수 있습니다. string을 반환할때도 있고, 객체를 반환할 때도 있어요

2021-06-18 10:49 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
`const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);`
이 친구는 왜 지우셨나용?? 선택 항목이 5개가 되면 선택 목록을 아예 안 보여주게 하는 방식이였는데 alert 알림으로 바꾸셨네용..?

2021-06-18 10:49 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> +        job: jobId,
null 처리는 백단에서 수행되니 그냥 보내시는 건가용?

2021-06-18 10:49 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -            options={isShowSkillOptions ? skillOptions : []}
왜 지웠엉 빼애애액

2021-06-18 10:49 UTC, bear-bear-bear commented on next/components/common/Label/index.tsx
> + * direction은 정의할 input의 상대적인 방향을 말합니다. 해당 방향으로 margin 이 적용됩니다.
편안0-

2021-06-18 10:53 UTC, galaxy4276 commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
코드 잘 확인해보세요

2021-06-18 10:55 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
첨부터 계속 확인해봤는데용..

2021-06-18 10:56 UTC, galaxy4276 commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
PR 내용도 확인해주세요

2021-06-18 10:57 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
아 저게 저거 말하는 거였나요

2021-06-18 10:57 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
UX 측면에서

2021-06-18 10:57 UTC, galaxy4276 commented on next/components/signup/OptionalInfo/index.tsx
> +        job: jobId,
맞습니다.

2021-06-18 10:57 UTC, galaxy4276 commented on next/components/signup/OptionalInfo/index.tsx
> -            options={isShowSkillOptions ? skillOptions : []}
PR 내용 확인해주세요.

2021-06-18 10:58 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
지금 alert로 띄워주는게 모달창이 되거나, 더 개선하면 해당 선택항목 옆에 span 같은걸로 경고문구가 표시 될텐데

2021-06-18 10:58 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
상당히 안 좋은 사용자 경험을 줄 것 같아요

2021-06-18 10:59 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
그래서 Select 옵션 자체를 없애는 쪽으로 코드 작성한 거에용

2021-06-18 10:59 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
5개 되는 순간 ㅎ

2021-06-18 11:00 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
근데 signup 페이지가 성능 상 문제가 나타나는 페이지도 아니라서

2021-06-18 11:00 UTC, bear-bear-bear commented on next/components/signup/OptionalInfo/index.tsx
> -  const [isShowSkillOptions, setIsShowSkillOptions] = useState(true);
UX를 챙길 수 있다면 이전 방법이 낫지 않을까요?

2021-06-18 12:20 UTC, bear-bear-bear approved these changes
감사합니다 수고하셨습니다

2021-06-18 12:26 UTC, merged