REFACTOR: 회원가입 > Start 페이지 리팩터링
bear-bear-bear/mogakco pull request #178
Opened 2021-06-22 17:45 UTC by galaxy4276

# Summary
* 불필요한 리렌더링 방지
* ref 타입 수정
* 페이지 코드 가독성 향상

2021-06-22 17:49 UTC, bear-bear-bear requested changes
고생하셨습니다 하나만 수정 부탁드려요 :)

2021-06-22 17:49 UTC, bear-bear-bear commented on next/components/signup/Start/index.tsx
> +  const submitButtonEl = createRef<HTMLButtonElement>();
![image](https://user-images.githubusercontent.com/57123802/122974470-51db1200-d3cd-11eb-8fd2-7177e916828a.png)
다시 useRef로 수정해주세요 ~
[참고주소](https://blog.bitsrc.io/react-useref-and-react-createref-the-difference-afedb9877d0f)

2021-06-22 17:54 UTC, galaxy4276 commented on next/components/signup/Start/index.tsx
> +  const submitButtonEl = createRef<HTMLButtonElement>();
만들어 주셨던 컴포넌트에 대해서 받는 ref 에 타입이 createRef 타입이라 그렇게 수정하긴 어려울 거 같습니다.
1 depth 면 간단하나, submitButton 에서 반환하는 Button 에서 반환하는 Button 에서 ref 를 그렇게 받도록 고정되어있네요.

2021-06-22 17:56 UTC, bear-bear-bear commented on next/components/signup/Start/index.tsx
> +  const submitButtonEl = createRef<HTMLButtonElement>();
![image](https://user-images.githubusercontent.com/57123802/122975704-9a46ff80-d3ce-11eb-91f8-7dc629776f2e.png)
해결법을 찾아야 할 것 같네요..

2021-06-22 17:56 UTC, bear-bear-bear commented on next/components/signup/Start/index.tsx
> +  const submitButtonEl = createRef<HTMLButtonElement>();
고생하셨어요 센빠이 일단 어서 주무세요

2021-06-22 18:07 UTC, galaxy4276 commented on next/components/signup/Start/index.tsx
> +  const submitButtonEl = createRef<HTMLButtonElement>();
해당사항 관련해서 ref 및 타입은 수정했으나, Button Type 쪽에서 타입문제가 심각한듯 합니다.

2021-06-22 18:08 UTC, bear-bear-bear commented on next/components/signup/Start/index.tsx
> +  const submitButtonEl = createRef<HTMLButtonElement>();
자라구우~

2021-06-23 06:18 UTC, galaxy4276 commented on next/components/signup/Start/index.tsx
> +  const submitButtonEl = createRef<HTMLButtonElement>();
해결

2021-06-23 10:09 UTC, bear-bear-bear approved these changes
마지막 커밋 체크 부탁드려요 고생하셨습니다

2021-06-23 10:16 UTC, merged

2021-06-23 10:16 UTC, bear-bear-bear commented
힝 내꺼지롱!