FIX: 기존 lib/Image를 next/Image로 교체
bear-bear-bear/mogakco pull request #183
Opened 2021-06-23 16:52 UTC by bear-bear-bear

* fix: 기존 lib/Image를 next/Image로 교체
* landing 페이지 관련 type에러 수정

2021-06-24 01:39 UTC, galaxy4276 requested changes

2021-06-24 01:39 UTC, galaxy4276 commented on next/components/landing/ContentBlock/index.tsx
> +  isFirstBlock?: boolean | undefined;
optional 인자를 주면 undefined 안줘도 될거에요.

2021-06-24 05:01 UTC, bear-bear-bear commented on next/components/landing/ContentBlock/index.tsx
> +  isFirstBlock?: boolean | undefined;
말씀하신걸로 알고있는데 이게 왜째선지 undefined 안 넣으면 에러나는 것 같더라구요..? 일단 내일 노트북 키먄 확인해보고 수정하겠습니다 감사합니다

2021-06-25 21:22 UTC, galaxy4276 approved these changes
❣

2021-06-26 07:37 UTC, merged