FEAT: 인증 정보에 따른 페이지 접근 제어 작업
bear-bear-bear/mogakco pull request #239
Opened 2021-07-10 10:52 UTC by bear-bear-bear

#238 에 기술된 내용 중 클라이언트의 작업
---
- [ ] next.config.js 설정
- [ ] 디렉터리 구조 변경
- [ ] 변경된 디렉터리 구조에 맞춰 경로 혹은 import 시의 @pages/ 이후의 경로 전부 수정

#238 에 기술된 내용 중 서버단의 작업
---
- [ ] 변경된 프론트 디렉터리구조 (url) 에 맞춰 프론트 단으로의 리다이렉션 경로 등 수정
- [ ] 로그인, 로그아웃에 따라 `x-authorized`라는 커스텀 헤더에 'true' 혹은 'false' 문자열을 매칭

2021-07-10 14:21 UTC, galaxy4276 approved these changes

2021-07-10 15:46 UTC, galaxy4276 commented on next/pages/_app.tsx
> +
로그인 되어있는 상태에서 첫 렌더링이 발생할 수 도 있는데 그부분은 다른데서 예외처리를 해주고있나요?

2021-07-10 15:48 UTC, galaxy4276 commented on next/pages/_app.tsx
> +
토큰 로그인 인증방식을 구현하고 있는데, 창을 종료하는 순간부터 로그아웃상태로 인식하게 끔 의도했다면 다시 생각해봐야 할 듯 해요. ( 세션 로그인 방식 )

2021-07-10 19:10 UTC, bear-bear-bear commented on next/pages/_app.tsx
> +
로그인 되어있는 상태에서  첫 렌더링은 생각치 못했네요 수정하겠습니다 세세한 검사 감사띠

2021-07-10 19:11 UTC, bear-bear-bear commented on next/pages/_app.tsx
> +
창을 종료하는 순간부터 로그아웃상태로 인식하게 끔 의도되진 않았습니다. 어느 부분에서 그렇게 생각하신건지..?

2021-07-10 21:14 UTC, galaxy4276 commented on next/pages/_app.tsx
> +
롤 한판하니까 머리가 돌아서 로직이 읽혔어요

2021-07-10 22:22 UTC, galaxy4276 requested changes

2021-07-10 22:22 UTC, galaxy4276 commented on next/pages/_app.tsx
> +      router.reload();
인증 상태의 첫 렌더링 여부 예외가 등록되지 않았음

2021-07-11 01:10 UTC, galaxy4276 approved these changes

2021-07-16 15:53 UTC, bear-bear-bear commented
https://github.com/bear-bear-bear/mogakco/pull/241

2021-07-16 15:53 UTC, bear-bear-bear commented
https://github.com/bear-bear-bear/mogakco/pull/241

2021-07-16 15:53 UTC, closed without merging