FEAT: 인증 정보에 따른 페이지 접근 제어 작업 (plan2)
bear-bear-bear/mogakco pull request #241
Opened 2021-07-14 14:50 UTC by bear-bear-bear

2021-07-15 21:17 UTC, bear-bear-bear commented
워낙 대규모 변경이라 파일 체인지 미안합니다

2021-07-16 01:07 UTC, galaxy4276 commented
PR 분리해주세요.
대규모 의미가 무엇인가요?
충분히 분리될 만 해보입니다.

2021-07-16 02:08 UTC, galaxy4276 commented on next/lib/token.ts
> +export const EXPIRATION = 'expiration';
typescript 는 상수관리에  enum 을 사용하면 좋아요.

2021-07-16 02:08 UTC, galaxy4276 commented on next/pages/api/auth/user.ts
> +  // });
테스트 용인가요?

2021-07-16 02:08 UTC, galaxy4276 commented on next/lib/token.ts
> +export const memoryStorage = new Map();
apiClient 에서 관리하는 부분을 분리하신건가요?

2021-07-16 02:10 UTC, galaxy4276 commented
코드를 읽어보니
1. 리팩터링 (async/await), 
2. 훅스 작성 및 반영 (useUser), 
3. token 시스템 분리 및 재작성

이런식으로 PR을 분리하면 편할거같습니다.
한 PR에 몰아서 작업할 이유는 크게 없어보이네요.

2021-07-16 03:25 UTC, galaxy4276 requested changes

2021-07-16 03:25 UTC, galaxy4276 commented on next/.eslintrc.js
> +        'no-shadow': 'off',
no-shadow 는 warn 으로라도 배치해두는게 좋을 듯 합니다.
off 는 lint 의미도 없어지고, 변수 스코프를 덮어씌우는건 좋지않으니까요

2021-07-16 03:32 UTC, galaxy4276 commented on next/.eslintrc.js
> +        'no-shadow': 'off',
아래 tslint 에서는 error 던데 혹시 다른 의도인가요?

2021-07-16 07:46 UTC, bear-bear-bear commented on next/.eslintrc.js
> +        'no-shadow': 'off',
https://typescript-eslint-armano.netlify.app/rules/no-shadow/
eslint의 no-shadow를 ts 환경으로 확장하기 위함입니다. 링크 참고해주세용 :)
기존 설정에선 enum 사용 시 무조건 warning을 뿜어냅니다.

2021-07-16 07:46 UTC, bear-bear-bear commented on next/lib/token.ts
> +export const memoryStorage = new Map();
넵 옮긴겁니다. 이 위치에서 관리하는게 적절하다 판단했습니다.

2021-07-16 07:46 UTC, bear-bear-bear commented on next/lib/token.ts
> +export const EXPIRATION = 'expiration';
찾아봤었는데,
enum - 서로 연관된 상수들을 하나의 namespace로 묶어 추상화
const || * as const - 리터럴 타입의 추론 범위를 줄이고 값의 재할당을 막아줌
연관된 상수 갯수가 많은게 아니라서 const 로 써도 상관 없다 판단했어요.

위 구문들을 
``` ts
export enum TOKEN {
  ACCESS_TOKEN = 'accessToken',
  EXPIRATION = 'expiration'
}
```
위와 같이 바꿔야 한다는 말씀이신데, TS상에서 제가 알지 못한 enum의 추가 이점이 있을까요?

2021-07-16 07:46 UTC, bear-bear-bear commented on next/pages/api/auth/user.ts
> +  // });
주석을 보라

2021-07-16 07:47 UTC, bear-bear-bear commented
> 코드를 읽어보니
> 리팩터링 (async/await),
> 훅스 작성 및 반영 (useUser),
> token 시스템 분리 및 재작성
> 이런식으로 PR을 분리하면 편할거같습니다.

아 이런식으로 분리하면 됐군요.. 유념하겠습니다.
담부턴 안되면 잘라서라도 올릴게요

2021-07-16 08:12 UTC, galaxy4276 commented on next/lib/token.ts
> +export const memoryStorage = new Map();
✔

2021-07-16 08:12 UTC, galaxy4276 commented on next/.eslintrc.js
> +        'no-shadow': 'off',
👍👍👍👍

2021-07-16 08:13 UTC, galaxy4276 commented on next/pages/api/auth/user.ts
> +  // });
👍👍👍👍👍

2021-07-16 08:13 UTC, galaxy4276 commented on next/lib/token.ts
> +export const EXPIRATION = 'expiration';
추가 이점은 없습니다.
프렌트엔드 황디벨로퍼님 판단이 맞습니다.

2021-07-16 14:20 UTC, bear-bear-bear commented
33커밋 27파일체인지 미안합니다 반성 👎

2021-07-16 15:32 UTC, galaxy4276 approved these changes

2021-07-16 15:52 UTC, merged