feat: 회원가입 UI 개발
bear-bear-bear/mogakco pull request #33
Opened 2021-04-03 07:46 UTC by wscrg

이메일 검증(Auth), 개인정보(이름, 비밀번호), 분야(개발 분야, 직업), 완료 부분을 컴포넌트화했고 SignUp 이라는 컴포넌트 하나로 통합시켰습니다. 그리고 SignUpContainer라는 하나의 컨테이너로  각 컴포넌트에 대한 처리를 prop으로 내려줘 상태가 변경되면 이전 컴포넌트는 사라지고 다음 컴포넌트를 보여주는 방식으로 할 예정입니다.

2021-04-03 09:03 UTC, galaxy4276 approved these changes
고생하셨습니다.

2021-04-03 11:15 UTC, quavious commented
프론트엔드 상태 변화 어려운데 고생하셨습니다.

2021-04-03 11:17 UTC, quavious approved these changes
프론트엔드 상태변화 고생하셨습니다. (승인)

2021-04-03 11:24 UTC, bear-bear-bear requested changes
04/03 스타일모듈 네이밍 컨벤션 관련 회의 후 approve 예정입니다

2021-04-03 11:24 UTC, bear-bear-bear commented on components/SignUp/Auth/index.js
> +        >
스타일은 한 줄이라도 style쪽으로 빼주는게 깔끔할 것 같아요 유지보수 적으로도

2021-04-03 11:25 UTC, galaxy4276 commented on components/SignUp/Auth/index.js
> +        >
매의 눈

2021-04-03 17:43 UTC, bear-bear-bear requested changes
reset 스타일은 이미 globalStyles에 추가되어 마스터에 반영된 상태입니다

2021-04-05 17:29 UTC, wscrg commented on components/SignUp/Auth/index.js
> +        >
useMemo로 처리했습니다

2021-04-06 02:57 UTC, bear-bear-bear approved these changes
사랑합니다

2021-04-06 03:02 UTC, merged

2021-04-06 06:36 UTC, galaxy4276 commented
머지 멈춰