feature: 랜딩 페이지 ui 작업 및 common 컴포넌트 다수 작성
bear-bear-bear/mogakco pull request #43
Opened 2021-04-12 16:43 UTC by bear-bear-bear

1. 랜딩 페이지 ui 작업 50% 완료

2. components/common/
    - Button 컴포넌트 작성
    - CustomHead 컴포넌트 작성
    - SvgImage 컴포넌트 작성

3. components/globalStyles/
    - media 객체 작성

2021-04-13 04:02 UTC, galaxy4276 requested changes

2021-04-13 04:02 UTC, galaxy4276 commented on components/common/CustomHead/index.js
> +CustomHead.propTypes = {
PropTypes 는 파일의 최상단에 배치하는게 좋습니다.
그래야 각 props 에 대한 정보를 확인하기 더 가독성이 좋습니다.
```suggestion
CustomHead.propTypes = {
```

2021-04-13 04:27 UTC, bear-bear-bear commented on components/common/CustomHead/index.js
> +CustomHead.propTypes = {
조언 너무 달달해요 하

2021-04-13 04:28 UTC, bear-bear-bear commented on components/common/CustomHead/index.js
> +CustomHead.propTypes = {
감사합니다. 말씀주신대로 작업하겠습니다

2021-04-13 04:28 UTC, bear-bear-bear commented on components/common/CustomHead/index.js
> +CustomHead.propTypes = {
조언 더해주세요 하아하아

2021-04-13 11:06 UTC, galaxy4276 approved these changes

2021-04-13 11:14 UTC, bear-bear-bear commented on components/common/CustomHead/index.js
> +CustomHead.propTypes = {
![image](https://user-images.githubusercontent.com/57123802/114543434-2bde1680-9c94-11eb-83c9-44df4cdf8652.png)

말씀해주신대로 작업시 TDZ 발생합니다 🙄

2021-04-14 15:21 UTC, wscrg approved these changes

2021-04-14 17:21 UTC, bear-bear-bear commented
* 랜딩 페이지 ui 작업 50% 완료

* components/common/
  - Button 컴포넌트 작성
  - CustomHead 컴포넌트 작성
  - SvgImage 컴포넌트 작성

* components/globalStyles/
  - media 객체 작성
  - 작성한 컴포넌트 사용법은 notion

2021-04-14 17:27 UTC, merged