time adventure
bear-bear-bear/mogakco pull request #51
Opened 2021-04-28 17:43 UTC by wscrg

2021-04-28 17:44 UTC, galaxy4276 approved these changes

2021-05-01 11:23 UTC, bear-bear-bear requested changes
redux/actions/landing/header.js
redux/selectors/landing/header.js

두개 파일 삭제해서 올려주세요! 빈 파일엔 코멘트가 불가능하여 여기 남깁니다.

2021-05-01 11:23 UTC, bear-bear-bear commented on components/SignUp/Interest/index.js
> +export default React.memo(Index);
props 없는 컴포넌트에서 React.memo() 사용

2021-05-01 11:23 UTC, bear-bear-bear commented on components/SignUp/ProgressBar/index.js
> +};
``` js
Index.propTypes = {
  fill: PropTypes.arrayOf(PropTypes.bool).isRequired,
};

export default Index;
```
프로퍼티 선언은 export 전에 해주세요. 왜냐구요? 저도 이유는 몰라요..

2021-05-01 11:23 UTC, bear-bear-bear commented on components/SignUp/ProgressBar/style.js
>    background-color: #e0e0de;
color, background-color 등 색 관련은 글로벌 Variables 를 사용해주세요. [노션문서참고](https://www.notion.so/_Variables-dbc742a92e844de6aeced73bc2f1a25c)

2021-05-01 11:23 UTC, bear-bear-bear commented on components/SignUp/ProgressBar/style.js
> +  backgroundColor: '#6a1b9a',
협의 없는 보라색. 멈춰! 메인컬러인 파란색으로 바꿔주세용 (글로벌 Variables)

2021-05-01 11:23 UTC, bear-bear-bear commented on redux/reducers/index.js
> +import signupReducer from './SignUp';
카멜케이스 규칙이 혼란스럽습니다. signup, signUp, SignUp, 무엇이 정답이냐!

2021-05-02 02:52 UTC, wscrg commented on components/SignUp/Auth/index.js
> +const emailRule = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;
알겠습니다!

2021-05-02 02:53 UTC, wscrg commented on components/SignUp/Auth/index.js
> +export default React.memo(Index);
수정하겠습니다.

2021-05-02 02:58 UTC, wscrg commented on components/SignUp/Auth/style.js
>  const fontColors = ['#A07575', '#ffffff'];
알겠습니다~

2021-05-02 03:17 UTC, wscrg commented on components/SignUp/Complete/index.js
>          <a>모각코 참여하러 가기</a>
UX를 평가하는 기준도 두면 좋을 것 같네요!

2021-05-02 03:20 UTC, wscrg commented on components/SignUp/Info/index.js
> +const passwordRule = /^(?=.*[A-Za-z])(?=.*\d)(?=.*[$@!%*#?&])[A-Za-z\d$@!%*#?&]{8,}$/;
옮겼습니다!

2021-05-02 03:30 UTC, wscrg commented on components/SignUp/Info/style.js
> +export default WarningText;
확인했습니다

2021-05-02 03:38 UTC, wscrg commented on components/SignUp/Interest/index.js
> +import { verifyInterestRequest } from '~/redux/actions/SignUp/interest';
규칙을 두면 좋죠! eslint 에러만 안 나게끔 썼었는데 그렇게 해보죠

2021-05-02 03:42 UTC, wscrg commented on components/SignUp/Interest/index.js
> +export default React.memo(Index);
수정

2021-05-02 03:47 UTC, wscrg commented on components/SignUp/Interest/style.js
>    color: #f13f31;
수정했습니다

2021-05-02 03:48 UTC, wscrg commented on components/SignUp/ProgressBar/style.js
>    background-color: #e0e0de;
수정했습니다

2021-05-02 03:48 UTC, wscrg commented on components/SignUp/ProgressBar/style.js
> +  backgroundColor: '#6a1b9a',
수정했습니다

2021-05-02 03:49 UTC, wscrg commented on components/SignUp/Info/index.js
> +import WarningText from './style';
수정했습니다

2021-05-02 03:59 UTC, wscrg commented on components/SignUp/Info/index.js
> +    }
이건.. 좋은데요?

2021-05-02 03:59 UTC, wscrg commented on components/SignUp/Info/index.js
> +  }, [term]);
옙

2021-05-02 04:05 UTC, wscrg commented on components/SignUp/Info/index.js
> +
이런 거 너무 좋아~

2021-05-02 04:06 UTC, wscrg commented on components/SignUp/Info/index.js
> +        )}
옙

2021-05-02 04:09 UTC, wscrg commented on components/SignUp/ProgressBar/index.js
> +};
알겠습니다. 왜냐구요? 저도 이유는 몰라요..

2021-05-02 05:22 UTC, bear-bear-bear commented on components/SignUp/Info/index.js
> +    }
``` js
if (!initSubmit) return;

if (term === false) {
  setTermError(true);
} else {
  setTermError(false);
}

if (passwordRule.test(password) === false) {
  setPasswordTestError(true);
} else {
  setPasswordTestError(false);
}

if (password !== passwordConfirm) {
  setPasswordMatchError(true);
} else {
  setPasswordMatchError(false);
}
```
첫줄 잘못썼었다

2021-05-02 06:14 UTC, bear-bear-bear requested changes
커밋 반영감사합니다! 

redux/actions/landing/header.js
redux/selectors/landing/header.js

두개 파일 삭제해서 올려주세요!

2021-05-02 06:24 UTC, bear-bear-bear approved these changes
고생하셨습니다 !!!

2021-05-02 06:24 UTC, merged