feat: signup 페이지 UI/UX 개선 및 잔버그 수정
bear-bear-bear/mogakco pull request #73
Opened 2021-05-24 19:14 UTC by bear-bear-bear

* UI 개선, 반응형 작업
 * auto focus 등 UX 개선
 * name convention 관련 잔버그 수정

![#73](https://user-images.githubusercontent.com/57123802/119396165-7af57d80-bd0f-11eb-8dac-7801b9598677.gif)

2021-05-24 22:47 UTC, galaxy4276 commented
출근 후 검토 예정

2021-05-25 00:48 UTC, galaxy4276 approved these changes
Files changed 15개 이하 유지해주세요.
( PR 잘라 올리기 )
두 분 올리는 PR이 30개가 넘어갈 때가 많습니다.
주의해주세요.

2021-05-25 00:48 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
unexpected alert 해결해주세요.

2021-05-25 00:48 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +  const [email, onChangeEmail, setEmail] = useInput('');
```suggestion
  const emailInputRef = useRef('');
```
email 상태에 대해 onChange 발생 시 리렌더링을 일으켜야 할 이유가 있나요?
아니라면 ref 로 관리하는게 성능 상 이점이 매우 클거에요.

2021-05-25 00:52 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +  const [email, onChangeEmail, setEmail] = useInput('');
useInput 에서 리턴하는 onChangeEmail 은 setEmail 에 단순히 useCallback 을 감싼 형태인가요?
그렇다면 연산 비용이 이렇게 될거에요.
onChangeEmail > setEmail

2021-05-25 00:55 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
useCallback 을 해줄 필요성 검토 부탁드립니다.
dispatch 는 스스로 memoizing 수행될 거에요.

2021-05-25 00:57 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
자세한 사항은 해당 이슈를 확인해주세요.
https://github.com/reduxjs/react-redux/issues/1468

2021-05-25 01:06 UTC, galaxy4276 requested changes

2021-05-25 01:06 UTC, galaxy4276 commented on components/landing/ContentBlock/LeftContentBlock/index.js
> +  const [email, onChangeEmail] = useInput('');
```suggestion
  const emailInputRef = useRef('');
```

이 부분도 ref 고려해주세요.

2021-05-25 04:39 UTC, bear-bear-bear commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
아 PR올릴때 커밋을 15개 이하 유지하라는게 아니라 file change를 15개 이하로 유지하는 거였군요 ㄷㄷ

2021-05-25 04:40 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
커밋도 15개입니다.

2021-05-25 06:02 UTC, bear-bear-bear commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
주의 하겠습니다

2021-05-25 06:02 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
이,,,사태가,,,주의로,,,,되겠읍니,까,,,?

2021-05-25 06:02 UTC, bear-bear-bear commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
dispatch는 수정할게요. 제로초..

2021-05-25 06:03 UTC, bear-bear-bear commented on components/signup/Auth/index.js
> +    alert('미구현 기능입니다');
unexpected alert는 개발 전 편의성을 위한 안내 문구입니다. 해당 기능 개발 중 사라질 코드입니다. 내용이 내용이다싶이 빠뜨릴 가능성 0

2021-05-26 00:52 UTC, galaxy4276 requested changes

2021-05-26 00:52 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +  const submitButtonEl = useRef(null);
```suggestion
  const emailRef = useRef(null);
  const submitButtonRef = useRef(null);
```
ref 변수 네이밍은 El보단 Ref 를 명시해주는 편입니다.

2021-05-26 00:53 UTC, galaxy4276 commented on components/signup/Auth/index.js
> +  const submitButtonEl = useRef(null);
해당 useRef 의 타입이 DOMElement 가 아닌 string 이기떄문에 더욱 맞는거 같습니다.

2021-05-26 01:34 UTC, bear-bear-bear commented
해당 useRef의 타입은 항상 DomElement |  null 입니다.
해당 ref에 담기는 ref.current.value는 항상 string 이구요.
그걸 dispatch 하기 전에 빈 문자열일 경우 null로 변환한겁니다 제 3의 변수에다가요. ref랑은 상관이 없지요.

변수명 말씀하신건 useRef 리액트 공식문서에서도 El과 Ref를 같이 사용하기 때문에 상관 없을 듯 합니다.

2021-05-26 01:36 UTC, galaxy4276 commented
> 해당 useRef의 타입은 항상 DomElement | null 입니다.
> 해당 ref에 담기는 ref.current.value는 항상 string 이구요.
> 그걸 dispatch 하기 전에 빈 문자열일 경우 null로 변환한겁니다 제 3의 변수에다가요. ref랑은 상관이 없지요.
> 
> 변수명 말씀하신건 useRef 리액트 공식문서에서도 El과 Ref를 같이 사용하기 때문에 상관 없을 듯 합니다.

S.컴포넌트에 ref 로 들어가는 점 확인하지 못했습니다.
잘못된 리퀘스트 미안합니다
승인!

2021-05-26 01:36 UTC, galaxy4276 approved these changes

2021-05-26 01:37 UTC, merged